name: HoneyGlazedFish
clonePrefabName: HoneyGlazedFish
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- FishRaw:1:1:True
- Honey:2:1:True
