name: Bandage_JH
clonePrefabName: Bandage_JH
craftingStation: ''
minStationLevel: 
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- WoolScraps_TW:5:1:True
- Resin:5:1:True
