name: FishRaw
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: true
upgrade_reqs: []
reqs:
- Fish1:1:1:True
- Fish2:1:1:True
- Fish3:1:1:True
- Fish4_cave:1:1:True
- Fish5:1:1:True
- Fish6:1:1:True
- Fish7:1:1:True
- Fish8:1:1:True
- Fish9:1:1:True
- Fish10:1:1:True
- Fish11:1:1:True
- Fish12:1:1:True
