name: MushroomSoup_JH
clonePrefabName: MushroomSoup_JH
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- Mushroom:5:1:True
- MushroomYellow:5:1:True
