name: Bandage2_JH
clonePrefabName: Bandage2_JH
craftingStation: ''
minStationLevel: 
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- GoblinScraps_TW:5:1:True
- Needle:5:1:True
- LinenThread:1:1:True
