name: WispPotion_JH
clonePrefabName: WispPotion_JH
craftingStation: $piece_meadcauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wisp:3:0:True
- MeadTasty:3:1:True
