name: WispPotion_JH
clonePrefabName: WispPotion_JH
craftingStation: $piece_cauldron
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
requireOnlyOneIngredient: false
reqs:
- Demister:1:0:True
- MeadTasty:3:1:True
