name: Bandage_JH
clonePrefabName: Bandage_JH
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- WoolScraps_TW:10:1:True
- Resin:5:1:True
