PrintComment: ThisGoesHere is deleting patches
DeleteFile:
- config\EpicLoot\patches\BruteWeapons\bw.iteminfo.json
- config\EpicLoot\patches\ChaosArmor\ca.iteminfo.json
- config\EpicLoot\patches\HugosArmory\ha.iteminfo.json
- config\EpicLoot\patches\HugosArmory\iteminfo.json
- config\EpicLoot\patches\JudesEquipment\iteminfo.json
- config\EpicLoot\patches\MagicBows\mb.iteminfo.json
- config\EpicLoot\patches\MagicPlugin\mp.iteminfo.json
- config\EpicLoot\patches\SouthsilArmor\sa.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\AdventureBackpacks\ad.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\BowPlugin\bp.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\BowsBeforeHoes\bfh.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\BruteWeapons\bw.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\ChaosArmor\ca.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\DragoonCapes\dg.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\ForsakenJVL\fjvl.loottables.json
- config\EpicLoot\patches\AllTheHeims\HugosArmory\ha.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\MagicBows\mb.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\MagicPlugin\mp.iteminfo.json
- config\EpicLoot\patches\AllTheHeims\SouthsilArmor\sa.iteminfo.json
DeleteFolder:
- config\EpicLoot\patches\MajesticBalances
- config\EpicLoot\patches\TherzieMods