name: eitrrefinery_JH_Tiny
piecehammer: Hammer
m_name: Small Eitr Refinery
sizeMultiplier: 0.6
m_description: ''
customIcon: 
clonePrefabName: eitrrefinery
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: TinyVersions
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: true
wearNTearData:
  health: 1000
  damageModifiers:
    m_blunt: Resistant
    m_slash: Resistant
    m_pierce: Resistant
    m_chop: Resistant
    m_pickaxe: Normal
    m_fire: Immune
    m_frost: Immune
    m_lightning: Ignore
    m_poison: Ignore
    m_spirit: Ignore
  noRoofWear: true
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
  materialType: Wood
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData:
  addOreTooltip: $piece_smelter_additem
  emptyOreTooltip: $piece_smelter_empty
  fuelItem:
    name: Sap
  maxOre: 50
  maxFuel: 50
  fuelPerProduct: 1
  secPerProduct: 40
  spawnStack: false
  requiresRoof: false
  addOreAnimationLength: 2
  smelterConversion:
  - FromName: Softtissue
    ToName: Eitr
    Remove: false
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
shieldGenData: 
batteringRamData: 
build:
- BlackMarble:20:1:True
- BlackMetal:5:1:True
- YggdrasilWood:10:1:True
- BlackCore:5:1:True
- Sap:3:1:True
