# Mountain
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_B
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_B
    amount: 1
  Items:
    - JC_Ring_Silver_band
    - JC_Necklace_Polished_silver_necklace
# Swamp
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_C
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_C
    amount: 1
  Items:
  - JC_Ring_Humite_Ring_of_Perception
# Meadows
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_F
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_F
    amount: 1
  Items:
  - JC_Ring_Bone_ring
  - JC_Ring_Stone_ring
  - JC_Necklace_Leather_cord  