- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_S
    amount: 2
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_S
    amount: 1
  Items:
  - AxeNjord_TW
  - AxeSurtr_TW
  - KnifeNjord_TW
  - KnifeSurtr_TW
  - MaceNjord_TW
  - MaceSurtr_TW
  - SpearNjord_TW
  - SpearSurtr_TW
  - SwordNjord_TW
  - SwordSurtr_TW
  - WarpikeNjord_TW
  - WarpikeSurtr_TW
  - DualAxeKrom_TW
  - BattleaxeCrystalJotunnheim_TW
  - BattleaxeCrystalMuspelheim_TW
  - DualSpearSvigaFrekk_TW
  - DualSwordSkadi_TW
  - BattleaxeDragon_TW
  - ClaymoreJotunn_TW
  - DualHammerStormstrike_TW
  - AtgeirNjord_TW
  - AtgeirSurtr_TW
  - BattleaxeNjord_TW
  - BattleaxeSurtr_TW
  - BattlehammerNjord_TW
  - BattlehammerSurtr_TW
  - BastardSurtr_TW
  - BastardNjord_TW
  - ClaymoreNjord_TW
  - ClaymoreSurtr_TW
  - GlacierBlade_TW
  - VolcanicBlade_TW
  - LightningBlade_TW
  - FistNjord_TW
  - FistSurtr_TW
  - DualHammerRageHatred_TW
  - SledgeNjord_TW
  - SledgeSurtr_TW
  - LanceNjord_TW
  - LanceSurtr_TW
  - StaffSkrymir_TW
  - StaffStorm_TW
  - PickaxeLokvyr_TW
  - BowNjord_TW
  - BowSurtr_TW
  - GreatbowNjord_TW
  - GreatbowSurtr_TW
  - CrossbowNjord_TW
  - CrossbowSurtr_TW
  - ShieldArcticSerpentscale_TW
  - ShieldNjordTower_TW
  - ShieldSurtrTower_TW
  - ShieldNjord_TW
  - ShieldSurtr_TW
  - ShieldNjordBuckler_TW
  - ShieldSurtrBuckler_TW
  - DualKnifeNjord_TW
  - DualKnifeSurtr_TW
  - StaffVulkarion_TW
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_S
    amount: 2
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_S
    amount: 1
  Items:
  - CapeDemon_TW
  - CapeNorth_TW
  - CapeSurtr_TW
  - CapeYmir_TW
  - CapeFenrir_TW
  - HelmetSpellslinger_Surtr_TW
  - HelmetRogueTyranium_TW
  - HelmetWarriorRagnorite_TW
  - HelmetRaiderRagnorite_TW
  - HelmetVidarTyranium_TW
  - HelmetFenrirThoradus_TW
  - HelmetLegionThoradus_TW
  - HelmetHunterTyranium_TW
  - ArmorSpellSlingerChest_Surtr_TW
  - ArmorRogueTyraniumChest_TW
  - ArmorWarriorRagnoriteChest_TW
  - ArmorRaiderRagnoriteChest_TW
  - ArmorVidarTyraniumChest_TW
  - ArmorFenrirThoradusChest_TW
  - ArmorLegionThoradusChest_TW
  - ArmorHunterChestTyranium_TW
  - ArmorSpellslingerLegs_Surtr_TW
  - ArmorRogueTyraniumLegs_TW
  - ArmorWarriorRagnoriteLegs_TW
  - ArmorRaiderRagnoriteLegs_TW
  - ArmorVidarTyraniumLegs_TW
  - ArmorFenrirThoradusLegs_TW
  - ArmorLegionThoradusLegs_TW
  - ArmorHunterLegsTyranium_TW