Name: PinnedModer
Status_m_name: $SE_Pinned_TW
Category: ''
IconName: CrippledIcon
ClonedSE: 
CustomIcon: 
FlashIcon: true
CooldownIcon: false
Tooltip: $SE_Pinned_description_TW
Attributes: None
StartMessageLoc: TopLeft
StartMessage: ''
StopMessageLoc: TopLeft
StopMessage: ''
RepeatMessageLoc: TopLeft
RepeatMessage: ''
RepeatInterval: 0
TimeToLive: 2
EndingStatusEffect: 
StartEffect_: 
StopEffect_: 
StartEffect_PLUS: []
StopEffect_PLUS: []
Cooldown: 0
ActivationAnimation: gpower
SeData:
  m_tickInterval: 0
  m_healthPerTickMinHealthPercentage: 0
  m_healthPerTick: 0
  m_healthOverTime: 0
  m_healthOverTimeDuration: 0
  m_healthOverTimeInterval: 0
  m_staminaOverTime: 0
  m_staminaOverTimeDuration: 0
  m_staminaDrainPerSec: 0
  m_runStaminaDrainModifier: 0
  m_jumpStaminaUseModifier: 0
  m_attackStaminaUseModifier: 0
  m_blockStaminaUseModifier: 0
  m_dodgeStaminaUseModifier: 0
  m_swimStaminaUseModifier: 0
  m_homeItemStaminaUseModifier: 0
  m_sneakStaminaUseModifier: 0
  m_runStaminaUseModifier: 0
  m_eitrOverTime: 0
  m_eitrOverTimeDuration: 0
  m_healthRegenMultiplier: 1
  m_staminaRegenMultiplier: 1
  m_eitrRegenMultiplier: 1
  m_raiseSkill: None
  m_raiseSkillModifier: 0
  m_skillLevel: None
  m_skillLevelModifier: 0
  m_skillLevel2: None
  m_skillLevelModifier2: 0
  m_mods: []
  m_modifyAttackSkill: All
  m_damageModifier: 1
  m_noiseModifier: 0
  m_stealthModifier: 0
  m_addMaxCarryWeight: 0
  m_speedModifier: -0.5
  m_jumpModifier:
    x: -1
    y: -1
    z: -1
    normalized: &o0
      x: -0.5773503
      y: -0.5773503
      z: -0.5773503
      normalized: *o0
      magnitude: 1
      sqrMagnitude: 0.9999999
    magnitude: 1.732051
    sqrMagnitude: 3
  m_maxMaxFallSpeed: 0
  m_fallDamageModifier: 0
  m_tickTimer: 0
  m_healthOverTimeTimer: 0
  m_healthOverTimeTicks: 0
  m_healthOverTimeTickHP: 0
  m_windMovementModifier: 0
SeShield: 
SePoison: 
SeFrost: 
