Name: Potion_LightFoot
Status_m_name: $item_mead_lightfoot
Category: arcanescroll
IconName: potion_lightfoot
ClonedSE: 
CustomIcon: 
FlashIcon: false
CooldownIcon: false
Tooltip: $se_potion_lightfoot_tooltip
Attributes: None
StartMessageLoc: Center
StartMessage: ''
StopMessageLoc: TopLeft
StopMessage: ''
RepeatMessageLoc: TopLeft
RepeatMessage: ''
RepeatInterval: 60
TimeToLive: 600
EndingStatusEffect: 
StartEffect_: 
StopEffect_: 
StartEffect_PLUS:
- name: sfx_Potion_health_Start
  m_enabled: true
  m_variant: -1
  m_attach: true
  m_follow: false
  m_inheritParentRotation: false
  m_inheritParentScale: false
  m_multiplyParentVisualScale: false
  m_randomRotation: false
  m_scale: true
  m_childTransform: ''
- name: vfx_LightFoot
  m_enabled: true
  m_variant: -1
  m_attach: true
  m_follow: false
  m_inheritParentRotation: false
  m_inheritParentScale: false
  m_multiplyParentVisualScale: false
  m_randomRotation: false
  m_scale: true
  m_childTransform: ''
StopEffect_PLUS: []
Cooldown: 0
ActivationAnimation: gpower
SeData:
  m_tickInterval: 0
  m_healthPerTickMinHealthPercentage: 0
  m_healthPerTick: 0
  m_healthOverTime: 0
  m_healthOverTimeDuration: 0
  m_healthOverTimeInterval: 0
  m_staminaOverTime: 0
  m_staminaOverTimeDuration: 0
  m_staminaDrainPerSec: 0
  m_runStaminaDrainModifier: 0
  m_jumpStaminaUseModifier: -0.3
  m_attackStaminaUseModifier: 0
  m_blockStaminaUseModifier: 0
  m_dodgeStaminaUseModifier: 0
  m_swimStaminaUseModifier: 0
  m_homeItemStaminaUseModifier: 0
  m_sneakStaminaUseModifier: 0
  m_runStaminaUseModifier: 0
  m_eitrOverTime: 0
  m_eitrOverTimeDuration: 0
  m_healthRegenMultiplier: 1
  m_staminaRegenMultiplier: 1
  m_eitrRegenMultiplier: 1
  m_raiseSkill: None
  m_raiseSkillModifier: 0
  m_skillLevel: None
  m_skillLevelModifier: 0
  m_skillLevel2: None
  m_skillLevelModifier2: 0
  m_mods: []
  m_modifyAttackSkill: None
  m_damageModifier: 1
  m_noiseModifier: 0
  m_stealthModifier: 0
  m_addMaxCarryWeight: 0
  m_speedModifier: 0
  m_jumpModifier:
    x: 0
    y: 0.2
    z: 0
    normalized: &o0
      x: 0
      y: 1
      z: 0
      normalized: *o0
      magnitude: 1
      sqrMagnitude: 1
    magnitude: 0.2
    sqrMagnitude: 0.04
  m_maxMaxFallSpeed: 0
  m_fallDamageModifier: 0
  m_tickTimer: 0
  m_healthOverTimeTimer: 0
  m_healthOverTimeTicks: 0
  m_healthOverTimeTickHP: 0
  m_windMovementModifier: 0
SeShield: 
SePoison: 
SeFrost: 
