name: ScytheVampiric_TW
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 7
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs:
- Iron:20:2
- Iron:40:3
- Iron:60:4
- Silver:20:5
- Silver:40:6
- Silver:60:7
- Silver:80:8
- BlackMetal:20:9
- BlackMetal:40:10
- BlackMetal:60:11
- BlackMetal:80:12
- WitheredBone:9:2
- WitheredBone:18:3
- WitheredBone:27:4
- SerpentScale:9:5
- SerpentScale:18:6
- SerpentScale:27:7
- SerpentScale:36:8
- LoxBone_TW:5:9
- LoxBone_TW:10:10
- LoxBone_TW:15:11
- LoxBone_TW:20:12
- Bloodbag:8:2
- Bloodbag:16:3
- Bloodbag:24:4
- FreezeGland:9:5
- FreezeGland:18:6
- FreezeGland:27:7
- FreezeGland:36:8
- GoblinTotem:5:9
- GoblinTotem:10:10
- GoblinTotem:15:11
- GoblinTotem:20:12
- TrophyVrykolathas_TW:1:2
- TrophyVrykolathas_TW:1:3
- TrophyVrykolathas_TW:1:4
- TrophySGolem:1:5
- TrophySGolem:1:6
- TrophySGolem:1:7
- TrophySGolem:1:8
- TrophyGoblinBrute:1:9
- TrophyGoblinBrute:1:10
- TrophyGoblinBrute:1:11
- TrophyGoblinBrute:1:12
reqs:
- Iron:40:20:True
- WitheredBone:18:9:True
- Bloodbag:16:8:True
- TrophyVrykolathas_TW:1:1:True
