name: BronzeDevastator_JH
clonePrefabName: BronzeDevastator_JH
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_forge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Bronze:12:6:True
- RoundLog:10:5:True
- BronzeNails:5:2:True
- TrophyGreydwarf:1:0:True
