name: StaffofHealing_JH
clonePrefabName: StaffofHealing_JH
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_wizardtable_TW
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- EnchantedWoodBlackForest_TW:10:0:True
- ShardElder_TW:3:0:True
- Bronze:20:0:True
- TrophyGreydwarfShaman:1:0:True
