name: FlametalDevastator_JH
clonePrefabName: FlametalDevastator_JH
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_blackforge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FlametalNew:30:15:True
- Blackwood:20:10:True
- GemstoneGreen:3:1:True
- TrophyCharredMelee:1:0:True
