name: IronDevastator_JH
clonePrefabName: IronDevastator_JH
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: $piece_forge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Iron:24:12:True
- ElderBark:15:8:True
- IronNails:5:2:True
- TrophyDraugr:1:0:True
