name: PickaxeStone_JH
clonePrefabName: PickaxeStone_JH
craftingStation: 
minStationLevel: 
maxStationLevelCap: 
repairStation: $piece_workbench
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:10:0:True
- Stone:5:0:True
