name: DvergrNeedle
clonePrefabName: DvergrNeedle
craftingStation: $piece_blackforge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_blackforge
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Iron:10:0:True
- BlackMarble:5:0:True
- Eitr:5:0:True
