name: TrophyGoldenAbomination
m_weight: 4
m_name: Golden Abomination Trophy
m_description: a rare drop, Haldor would buy this for a hefty price                     <color=#edd221>Valuable</color>
clonePrefabName: TrophyAbomination
mockName: 
customIcon: 
material: coin
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
m_maxStackSize: 100
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
Attach_Override: None
m_skillType: Swords
m_animationState: OneHanded
m_itemType: Misc
m_toolTier: 0
m_maxQuality: 1
m_value: 125
