name: GB_Castle_Hearth_JH
piecehammer: Hammer
m_name: Castle Hearth
sizeMultiplier: 1
m_description: Quiet Smokeless Hearth
customIcon: 
clonePrefabName: GB_Castle_Hearth
material: 
damagedMaterial: 
craftingStation: $piece_stonecutter
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort:
  comfort: 2
  comfortGroup: Fire
  comfortObject: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 1000
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData:
  StartFuel: 5
  MaxFuel: 100
  SecPerFuel: 10000
  InfiniteFuel: false
  FuelType: Wood
  IgniteInterval: 0
  IgniteChance: 0
  IgniteSpread: 4
teleportWorldData: 
plantData: 
build:
- Stone:15:1:True
