name: GB_Fire_Pit_JH
piecehammer: Hammer
m_name: Castle Campfire
sizeMultiplier: 1
m_description: Quiet Smokeless Campfire, better than the Campfire
customIcon: 
clonePrefabName: GB_Fire_Pit
material: 
damagedMaterial: 
craftingStation: 
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
  comfort: 1
  comfortGroup: Fire
  comfortObject: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: true
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 100
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData:
  StartFuel: 5
  MaxFuel: 100
  SecPerFuel: 10000
  InfiniteFuel: true
  FuelType: Wood
  IgniteInterval: 0
  IgniteChance: 0
  IgniteSpread: 4
teleportWorldData: 
plantData: 
build:
- Stone:5:1:True
- Wood:2:1:True
