1:
  success: 95
2:
  success: 90
3:
  success: 85
4:
  success: 80
5:
  success: 75
6:
  success: 70
7:
  success: 65
8:
  success: 60
9:
  success: 55
10:
  success: 50
11:
  success: 40
12:
  success: 30
13:
  success: 20
14:
  success: 10
15:
  success: 8
16:
  success: 6
17:
  success: 4
18:
  success: 2
19:
  success: 1