1:
  damage_percentage: 2
2:
  damage_percentage: 3
3:
  damage_percentage: 4
4:
  damage_percentage: 5
5:
  damage_percentage: 6
6:
  damage_percentage: 7
7:
  damage_percentage: 9
8:
  damage_percentage: 11
9:
  damage_percentage: 13
10:
  damage_percentage: 15
11:
  damage_percentage: 17
12:
  damage_percentage: 19
13:
  damage_percentage: 22
14:
  damage_percentage: 25
15:
  damage_percentage: 28
16:
  damage_percentage: 31
17:
  damage_percentage: 35
18:
  damage_percentage: 39
19:
  damage_percentage: 44
20:
  damage_percentage: 50
