1:
  damage_percentage: 4
2:
  damage_percentage: 6
3:
  damage_percentage: 8
4:
  damage_percentage: 10
5:
  damage_percentage: 12
6:
  damage_percentage: 14
7:
  damage_percentage: 18
8:
  damage_percentage: 22
9:
  damage_percentage: 26
10:
  damage_percentage: 30
11:
  damage_percentage: 37
12:
  damage_percentage: 38
13:
  damage_percentage: 44
14:
  damage_percentage: 50
15:
  damage_percentage: 56
16:
  damage_percentage: 62
17:
  damage_percentage: 70
18:
  damage_percentage: 78
19:
  damage_percentage: 88
20:
  damage_percentage: 100
