- Items:
  - ShieldBanded
  - ShieldBlackmetal
  - ShieldBlackmetalTower
  - ShieldBoneTower
  - ShieldBronzeBuckler
  - ShieldCarapace
  - ShieldCarapaceBuckler
  - ShieldFlametal
  - ShieldFlametalTower
  - ShieldIronBuckler
  - ShieldIronTower
  - ShieldSerpentscale
  - ShieldSilver
  - ShieldWood
  - ShieldWoodTower
  - ShieldBronzeBanded_TW
  - ShieldBronzeTower_TW
  - ShieldChitin_TW
  - ShieldChitinTower_TW
  - ShieldChitinBuckler_TW
  - ShieldSilverBuckler_TW
  - ShieldBlackmetalBuckler_TW
  - ShieldCarapaceTower_TW
  - ShieldArcticSerpentscale_TW
  - ShieldNjordTower_TW
  - ShieldSurtrTower_TW
  - ShieldNjord_TW
  - ShieldSurtr_TW
  - ShieldNjordBuckler_TW
  - ShieldSurtrBuckler_TW
  Stats:
    1:
      armor: 1
    2:
      armor: 2
    3:
      armor: 3
    4:
      armor: 4
    5:
      armor: 5
    6:
      armor: 6
    7:
      armor: 7
    8:
      armor: 8
    9:
      armor: 9
    10:
      armor: 10
    11:
      armor: 11
    12:
      armor: 12
    13:
      armor: 13
    14:
      armor: 14
    15:
      armor: 15
    16:
      armor: 15
    17:
      armor: 15
    18:
      armor: 15
    19:
      armor: 15
    20:
      armor: 15