Abomination: Boss
Troll: Boss
StoneGolem: Boss
Lox: Boss
Skeleton_Poison: Boss
BlobTar: Boss
Hatchling: Boss
GoblinBrute: Boss
Serpent: Boss
# Monstrum:
ObsidianGolem_TW: Boss
Shark_TW: Boss
# Monstrum_DeepNorth
ArcticBear_TW: Boss
ArcticWolf_TW: Boss
ArcticMammoth_TW: Boss
ArcticSerpent_TW: Boss
ArcticGolem_TW: Boss
StormCultist_TW: Boss
StormFenring_TW: Boss
JotunnBrute_TW: Boss
JotunnJuggernaut_TW: Boss
JotunnBladefist_TW: Boss
JotunnShaman_TW: Boss
JotunnWolf_TW: Boss
StormWolf_TW: Boss
# Wizardry:
GreydwarfMage_TW: Boss
SkeletonMage_TW: Boss
FenringMage_TW: Boss
GoblinMage_TW: Boss
CorruptedDvergerMage_TW: Boss
SummonedSeeker_TW: Boss

#Factions:
#Players
#AnimalsVeg
#ForestMonsters
#Undead
#Demon
#MountainMonsters
#SeaMonsters
#PlainsMonsters
#Boss
#MistlandsMonsters
#Dverger