Explorers Backpack:
  description: "A simple backpack that can be taken on adventures."
  size: 5x3
  appearance:
    Sleepbag: visible
    BackpackFlap: visible
    RingBottomLeft: visible
    MetalclipLeft: visible
    ToolstrapTop: visible
    PouchFront: visible
    PouchLeft: visible
    Knifesheath: visible
    Knife: visible
    Pickaxe: visible
    Pot: visible
    Teapot: visible
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: visible
    BackpackStrapTop: visible
    BackpackStrapBottom: visible
    ToolstrapBottom: visible
  valid items:
   - ore
   - metal
   - food
   - potion
   - woods
   - trophy
   - boss trophy
   - valuable
   - seed
   - crop
   - stackable
   - ammo
  weight factor: 0.9
  crafting:
    station: Workbench
    level: 1
    costs:
      BronzeNails: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 6x3
    2:
      Silver: 5
      WolfPelt: 3
      JuteRed: 2
      size: 5x4
    3:
      BlackMetal: 5
      LinenThread: 10
      LoxPelt: 2
      size: 6x4
    4:
      JuteBlue: 5
      ScaleHide: 5
      Carapace: 5
      size: 7x4
Simple Backpack:
  description: "A simple backpack capable of holding a few items"
  size: 2x2
  appearance:
    Sleepbag: visible
    BackpackFlap: 000000
    RingBottomLeft: e33900
    MetalclipLeft: hidden
    ToolstrapTop: e33900
    PouchFront: 000000
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: f2fc32
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: f2fc32
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: e33900
  valid items:
   - ore
   - metal
   - food
   - potion
   - woods
   - trophy
   - boss trophy
   - valuable
   - seed
   - crop
   - stackable
   - ammo
  weight factor: 0.9
  crafting:
    station: Workbench
    level: 1
    costs:
      DeerHide: 10
      LeatherScraps: 5
  upgrade:
    1:
      DeerHide: 10
      LeatherScraps: 5
      size: 3x2
Mining Backpack:
  description: "This backpack will only hold Ores and Metals, helps reduce the weight."
  size: 3x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: e33900
    RingBottomLeft: e33900
    MetalclipLeft: hidden
    ToolstrapTop: e33900
    PouchFront: e33900
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: f2fc32
    Pot: e33900
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: f2fc32
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: e33900
  valid items:
    - ore
    - metal
    - ThoradusBar_TW
    - TyraniumBar_TW
    - RagnoriteBar_TW
    - LokvyrBar_TW
    - LokvyrOre_TW
    - RagnoriteOre_TW
    - TyraniumOre_TW
  weight factor: 0.75
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 4x3
    2:
      Silver: 5
      WolfPelt: 10
      JuteRed: 5
      size: 5x3 
    3:
      BlackMetal: 5
      LinenThread: 10
      LoxPelt: 5
      size: 5x4
    4:
      Iron: 5
      Carapace: 10
      Mandible: 5
      size: 6x4
Foraging Backpack:
  description: "This backpack will only hold Wood and Rock types, helps reduce the weight."
  size: 3x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: 4d3209
    RingBottomLeft: 4d3209
    MetalclipLeft: hidden
    ToolstrapTop: 4d3209
    PouchFront: 4d3209
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: 71fa52
    Pot: 4d3209
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: 71fa52
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: 4d3209
  valid items:
    - Wood
    - ElderBark
    - RoundLog
    - FineWood
    - YggdrasilWood
    - Blackwood
    - Stone
    - BlackMarble
    - Flint
    - Coal
    - SulfurStone
    - Grausten
    - BeechSeeds
    - BirchSeeds
    - AncientSeed
    - Acorn
    - FirCone
    - PineCone
    - VineberrySeeds
    - EnchantedWoodBlackForest_TW
    - EnchantedWoodSwamp_TW
    - EnchantedWoodMountain_TW
    - EnchantedWoodPlains_TW
    - EnchantedWoodMistlands_TW
    - BorealWood_TW
    - BorealPineWood_TW
    - GlacierStone_TW
  weight factor: 0.5
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 4x3
    2:
      Silver: 5
      WolfPelt: 10
      JuteRed: 5
      size: 5x3 
    3:
      BlackMetal: 5
      LinenThread: 10
      LoxPelt: 5
      size: 5x4
    4:
      BronzeScrap: 5
      Carapace: 10
      Mandible: 5
      size: 6x4
Treasures Backpack:
  description: "This backpack will only hold coins and other valuables, helps reduce the weight."
  size: 4x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: f2fc32
    RingBottomLeft: f2fc32
    MetalclipLeft: hidden
    ToolstrapTop: f2fc32
    PouchFront: f2fc32
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: f2fc32
    Pot: f2fc32
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: f2fc32
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: f2fc32
  valid items:
   - valuable
  weight factor: 0.5
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 4x4
Troll Backpack:
  description: "The troll armor has been tucked away tightly inside its pouches granting users the power of Sneak"
  size: 3x3
  effect: SetEffect_TrollArmor
  appearance:
    Sleepbag: hidden
    BackpackFlap: 34baeb
    RingBottomLeft: 34baeb
    MetalclipLeft: hidden
    ToolstrapTop: 34baeb
    PouchFront: 34baeb
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: yellow
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: black
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: 34baeb
  valid items:
   - ore
   - metal
   - food
   - potion
   - woods
   - trophy
   - boss trophy
   - valuable
   - seed
   - crop
   - stackable
   - ammo
  weight factor: 0.9
  crafting:
    station: Forge
    level: 1
    costs:
      HelmetTrollLeather: 1
      ArmorTrollLeatherChest: 1
      ArmorTrollLeatherLegs: 1
      CapeTrollHide: 1
  upgrade:
    1:
      TrollHide: 5
      BoneFragments: 3
      Iron: 10
      size: 4x3
    2:
      TrollHide: 10
      BoneFragments: 6
      Silver: 10
      size: 5x3 
    3:
      TrollHide: 15
      BoneFragments: 9
      BlackMetal: 10
      size: 5x4
    4:
      TrollHide: 20
      BoneFragments: 12
      Carapace: 10
      size: 6x4
Food Backpack:
  description: "This backpack will only hold your food"
  size: 4x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: visible
    RingBottomLeft: visible
    MetalclipLeft: hidden
    ToolstrapTop: visible
    PouchFront: visible
    PouchLeft: hidden
    Knifesheath: visible
    Knife: visible
    Pickaxe: hidden
    Pot: visible
    Teapot: visible
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: 000000
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: visible
  valid items:
    - NeckTail
    - SerpentMeat
    - BoneMawSerpentMeat
    - CookedEntrails
    - HoneyGlazedDeer
    - HoneyGlazedMeat
    - HoneyGlazedNeck
    - HoneyGlazedLox
    - HoneyGlazedWolf
    - JellyGlazedHare
    - JellyGlazedSeeker
    - CookedEntrails
    - LoxJerky_JH
    - SeekerJerky_JH
    - FishJerky_JH
    - FishStew_JH
    - NeckJerky_JH
    - SerpentJerky_JH
    - FishMeatSkewer
    - FishNLoxSkewer
    - SharkMeat_TW
    - SharkFin_TW
    - ArcticSerpentMeat_TW
    - UncookedBerryCakePlains_TW
    - MushroomWitcheye_TW
    - MushroomDeathcap_TW
    - MushroomWizardbutter_TW
    - MushroomDevilstongue_TW
    - food
  weight factor: 1
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 5x3
Trophy Backpack:
  description: "This backpack will only hold the head of your enemies."
  size: 6x4
  appearance:
    Sleepbag: hidden
    BackpackFlap: fcc1ff
    RingBottomLeft: e33900
    MetalclipLeft: hidden
    ToolstrapTop: e33900
    PouchFront: fcc1ff
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: hidden
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: 8a2be2
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: e33900
  valid items:
    - trophy
    - boss trophy
  weight factor: 1
  crafting:
    station: Workbench
    level: 2
    costs:
      DeerHide: 10
      LeatherScraps: 5
  upgrade:
    1:
      DeerHide: 10
      LeatherScraps: 5
      size: 7x4
Scroll Backpack:
  description: "This backpack will only hold enchanting scrolls"
  size: 2x4
  appearance:
    Sleepbag: hidden
    BackpackFlap: visible
    RingBottomLeft: visible
    MetalclipLeft: hidden
    ToolstrapTop: visible
    PouchFront: visible
    PouchLeft: hidden
    Knifesheath: visible
    Knife: visible
    Pickaxe: hidden
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: de8359
    BackpackStrapTop: hidden
    BackpackStrapBottom: de8359
    ToolstrapBottom: visible
  valid items:
    - kg_EnchantScroll_Armor_S
    - kg_EnchantScroll_Armor_Blessed_S
    - kg_EnchantScroll_Weapon_S
    - kg_EnchantScroll_Weapon_Blessed_S
    - kg_EnchantScroll_Armor_A
    - kg_EnchantScroll_Armor_Blessed_A
    - kg_EnchantScroll_Weapon_A
    - kg_EnchantScroll_Weapon_Blessed_A
    - kg_EnchantScroll_Armor_B
    - kg_EnchantScroll_Armor_Blessed_B
    - kg_EnchantScroll_Weapon_B
    - kg_EnchantScroll_Weapon_Blessed_B
    - kg_EnchantScroll_Armor_C
    - kg_EnchantScroll_Armor_Blessed_C
    - kg_EnchantScroll_Weapon_C
    - kg_EnchantScroll_Weapon_Blessed_C
    - kg_EnchantScroll_Armor_D
    - kg_EnchantScroll_Armor_Blessed_D
    - kg_EnchantScroll_Weapon_D
    - kg_EnchantScroll_Weapon_Blessed_D
    - kg_EnchantScroll_Armor_F
    - kg_EnchantScroll_Armor_Blessed_F
    - kg_EnchantScroll_Weapon_F
    - kg_EnchantScroll_Weapon_Blessed_F
  weight factor: 1
  crafting:
    station: Workbench
    level: 1
    costs:
      DeerHide: 10
      LeatherScraps: 5
  upgrade:
    1:
      BlackBearPelt_TW: 5
      Bronze: 2
      size: 3x4
    2:
      RottenPelt_TW: 5
      Iron: 2
      size: 4x4
    3:
      GrizzlyBearPelt_TW: 5
      Silver: 2
      size: 5x4
    4:
      LoxPelt: 5
      BlackMetal: 2
      size: 6x4
Ammo Backpack:
  description: "This backpack will only hold ammo, you cannot use them from within"
  size: 6x4
  appearance:
    Sleepbag: hidden
    BackpackFlap: ffebb0
    RingBottomLeft: e06666
    MetalclipLeft: hidden
    ToolstrapTop: hidden
    PouchFront: ffebb0
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: hidden
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: e06666
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: hidden
  weight factor: 1
  valid items:
    - ammo
  crafting:
    station: Workbench
    level: 2
    costs:
      DeerHide: 10
      LeatherScraps: 5
  upgrade:
    1:
      DeerHide: 10
      LeatherScraps: 5
      size: 7x4
Wishbone Backpack:
  description: "The wishbone has been tucked away tightly inside its pouches granting users the power of finding hidden things."
  size: 5x3
  effect: Wishbone
  appearance:
    BackpackFlap: 68e4d9
    PouchFront: 68e4d9
    BackpackStrapBottom: 68e4d9
    RingBottomLeft: 000000
    BackpackBody: visible
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    Sleepbag: hidden
    MetalclipLeft: hidden
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: hidden
    Pot: hidden
    Teapot: hidden
    BackpackStrapTop: hidden
    ToolstrapTop: hidden
    ToolstrapBottom: hidden
  valid items:
   - ore
   - metal
   - food
   - potion
   - woods
   - trophy
   - boss trophy
   - valuable
   - seed
   - crop
   - stackable
   - ammo
  weight factor: 0.9
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
      Wishbone: 1
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 6x3
    2:
      Silver: 5
      WolfPelt: 3
      JuteRed: 2
      size: 5x4
    3:
      BlackMetal: 5
      LinenThread: 10
      LoxPelt: 2
      size: 6x4
    4:
      JuteBlue: 5
      ScaleHide: 5
      Carapace: 5
      size: 7x4