Simple Backpack:
  description: "A simple backpack capable of holding a few items"
  size: 2x2
  appearance:
    Sleepbag: visible
    BackpackFlap: 000000
    RingBottomLeft: e33900
    MetalclipLeft: hidden
    ToolstrapTop: e33900
    PouchFront: 000000
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: f2fc32
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: f2fc32
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: e33900
  weight factor: 0.9
  crafting:
    station: Workbench
    level: 2
    costs:
      DeerHide: 10
      LeatherScraps: 5
  upgrade:
    1:
      DeerHide: 10
      LeatherScraps: 5
      size: 3x2
Mining Backpack:
  description: "This backpack will only hold Ores and Metals, helps reduce the weight."
  size: 3x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: e33900
    RingBottomLeft: e33900
    MetalclipLeft: hidden
    ToolstrapTop: e33900
    PouchFront: e33900
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: f2fc32
    Pot: e33900
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: f2fc32
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: e33900
  valid items:
    - CopperOre
    - Copper
    - CopperScrap
    - TinOre
    - Tin
    - BronzeScrap
    - Bronze
    - SilverOre
    - Silver
    - IronScrap
    - Iron
    - BlackMetalScrap
    - BlackMetal
    - FlametalOreNew
    - FlametalNew
  weight factor: 0.7
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 4x3
    2:
      Silver: 5
      WolfPelt: 10
      JuteRed: 5
      size: 5x3 
    3:
      BlackMetal: 5
      LinenThread: 10
      LoxPelt: 5
      size: 5x4
    4:
      Iron: 5
      Carapace: 10
      Mandible: 5
      size: 6x4
Lumberjack Backpack:
  description: "This backpack will only hold Wood types, helps reduce the weight."
  size: 3x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: 4d3209
    RingBottomLeft: 4d3209
    MetalclipLeft: hidden
    ToolstrapTop: 4d3209
    PouchFront: 4d3209
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: f2fc32
    Pot: 4d3209
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: f2fc32
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: 4d3209
  valid items:
    - Wood
    - ElderBark
    - RoundLog
    - FineWood
    - YggdrasilWood
    - Blackwood
    - EnchantedWoodBlackForest_TW
    - EnchantedWoodSwamp_TW
    - EnchantedWoodMountain_TW
    - EnchantedWoodPlains_TW
    - EnchantedWoodMistlands_TW
  weight factor: 0.5
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 4x3
    2:
      Silver: 5
      WolfPelt: 10
      JuteRed: 5
      size: 5x3 
    3:
      BlackMetal: 5
      LinenThread: 10
      LoxPelt: 5
      size: 5x4
    4:
      Iron: 5
      Carapace: 10
      Mandible: 5
      size: 6x4
Treasures Backpack:
  description: "This backpack will only hold coins and other valuables, helps reduce the weight."
  size: 4x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: f2fc32
    RingBottomLeft: f2fc32
    MetalclipLeft: hidden
    ToolstrapTop: f2fc32
    PouchFront: f2fc32
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: f2fc32
    Pot: f2fc32
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: f2fc32
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: f2fc32
  valid items:
   - valuable
  weight factor: 0.5
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 4x4
Foraging Backpack:
  description: "This backpack will only hold Wood and Rock types, helps reduce the weight."
  size: 3x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: 4d3209
    RingBottomLeft: 4d3209
    MetalclipLeft: hidden
    ToolstrapTop: 4d3209
    PouchFront: 4d3209
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: 71fa52
    Pot: 4d3209
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: 71fa52
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: 4d3209
  valid items:
    - Wood
    - ElderBark
    - RoundLog
    - FineWood
    - YggdrasilWood
    - Blackwood
    - EnchantedWoodBlackForest_TW
    - EnchantedWoodSwamp_TW
    - EnchantedWoodMountain_TW
    - EnchantedWoodPlains_TW
    - EnchantedWoodMistlands_TW
    - Stone
    - BlackMarble
    - Flint
    - Coal
    - SulfurStone
    - Grausten
    - BeechSeeds
    - BirchSeeds
    - AncientSeed
    - Acorn
    - FirCone
    - PineCone
    - VineberrySeeds
  weight factor: 0.5
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 4x3
    2:
      Silver: 5
      WolfPelt: 10
      JuteRed: 5
      size: 5x3 
    3:
      BlackMetal: 5
      LinenThread: 10
      LoxPelt: 5
      size: 5x4
    4:
      BronzeScrap: 5
      Carapace: 10
      Mandible: 5
      size: 6x4
Troll Backpack:
  description: "The troll armor has been tucked away tightly inside its pouches granting users the power of Sneak"
  size: 3x3
  effect: SetEffect_TrollArmor
  appearance:
    Sleepbag: hidden
    BackpackFlap: 34baeb
    RingBottomLeft: 34baeb
    MetalclipLeft: hidden
    ToolstrapTop: 34baeb
    PouchFront: 34baeb
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: yellow
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: black
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: 34baeb
  weight factor: 0.8
  crafting:
    station: Forge
    level: 1
    costs:
      HelmetTrollLeather: 1
      ArmorTrollLeatherChest: 1
      ArmorTrollLeatherLegs: 1
      CapeTrollHide: 1
  upgrade:
    1:
      TrollHide: 5
      BoneFragments: 3
      Iron: 10
      size: 4x3
    2:
      TrollHide: 10
      BoneFragments: 6
      Silver: 10
      size: 5x3 
    3:
      TrollHide: 15
      BoneFragments: 9
      BlackMetal: 10
      size: 5x4
    4:
      TrollHide: 20
      BoneFragments: 12
      Carapace: 10
      size: 6x4
# Weapons and Armor Backpacks
Armory Backpack:
  description: "This backpack will hold a lot of your unused armor"
  size: 6x4
  appearance:
    Sleepbag: f44336
    BackpackFlap: f44336
    RingBottomLeft: f44336
    MetalclipLeft: hidden
    ToolstrapTop: f44336
    PouchFront: f44336
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: yellow
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: black
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: f44336
  valid items:
    - helmet
    - chest
    - pants
    - cape
    - armor
  weight factor: 1
  crafting:
    station: Forge
    level: 1
    costs:
      LeatherScraps: 10
      DeerHide: 10
      BronzeNails: 5
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 7x4
Weaponry Backpack:
  description: "This backpack will hold a lot of your unused weapons"
  size: 6x4
  appearance:
    Sleepbag: ca5df5
    BackpackFlap: ca5df5
    RingBottomLeft: ca5df5
    MetalclipLeft: hidden
    ToolstrapTop: ca5df5
    PouchFront: ca5df5
    PouchLeft: hidden
    Knifesheath: hidden
    Knife: hidden
    Pickaxe: yellow
    Pot: hidden
    Teapot: hidden
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: black
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: ca5df5
  valid items:
    - axes
    - clubs
    - knives
    - pickaxes
    - polearms
    - spears
    - swords
    - bows
    - crossbows
    - weapon
    - round shield
    - tower shield
    - shield
    - tool
    - special
    - arrows
    - bolts
    - FistFenrirClaw
    - FistFlint_TW
    - FistSilver_TW
    - FistBlackmetal_TW
    - FistQueen_TW
    - FistBronze_TW
    - FistChitin_TW
    - FistIron_TW
    - FistBlackmetal_TW
    - FistDvergr_TW
  weight factor: 1
  crafting:
    station: Forge
    level: 1
    costs:
      LeatherScraps: 10
      DeerHide: 10
      BronzeNails: 5
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 7x4
Food Backpack:
  description: "This backpack will only hold your food"
  size: 4x3
  appearance:
    Sleepbag: hidden
    BackpackFlap: visible
    RingBottomLeft: visible
    MetalclipLeft: hidden
    ToolstrapTop: visible
    PouchFront: visible
    PouchLeft: hidden
    Knifesheath: visible
    Knife: visible
    Pickaxe: hidden
    Pot: visible
    Teapot: visible
    MetalclipFrontLeft: visible
    MetalclipFrontRight: visible
    BackpackBody: 000000
    BackpackStrapTop: hidden
    BackpackStrapBottom: 000000
    ToolstrapBottom: visible
  valid items:
    - NeckTail
    - SerpentMeat
    - CookedEntrails
    - HoneyGlazedDeer
    - HoneyGlazedMeat
    - HoneyGlazedNeck
    - HoneyGlazedLox
    - HoneyGlazedWolf
    - JellyGlazedHare
    - JellyGlazedSeeker
    - CookedEntrails
    - ElkJerky
    - LoxJerky_JH
    - SeekerJerky_JH
    - FishJerky_JH
    - FishStew_JH
    - NeckJerky_JH
    - SerpentJerky_JH
    - FishMeatSkewer
    - FishNLoxSkewer
    - food
  weight factor: 0.8
  crafting:
    station: Forge
    level: 1
    costs:
      Bronze: 5
      DeerHide: 10
      LeatherScraps: 10
  upgrade:
    1:
      Iron: 5
      ElderBark: 10
      Guck: 2
      size: 5x3