## Creatures in biomes get increase chance of Aggressive and Spirit once that biomes boss is killed
Meadows:
  key_defeated_eikthyr:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

BlackForest:
  key_defeated_gdking:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

Swamp:
  key_defeated_Bonemass:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

Mountain:
  key_defeated_Dragon:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

Plains:
  key_defeated_goblinking:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

Mistlands:
  key_defeated_queen:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

Ashlands:
  key_defeated_fader:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

## Therzies Creatures in biomes get increase chance of Aggressive and Spirit once that biomes boss is killed
MeadowsTherzie:
  key_defeated_eikthyr:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

BlackForestTherzie:
  key_defeated_gdking:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

SwampTherzie:
  key_defeated_Bonemass:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

MountainTherzie:
  key_defeated_Dragon:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

PlainsTherzie:
  key_defeated_goblinking:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]

MistlandsTherzie:
  key_defeated_queen:
   effect:
    Aggressive: [30, 35, 40, 45, 50]
   infusion:
    Spirit: [0, 0, 0, 0, 0]
    Chaos: [0, 0, 0, 0, 0]