Fox_TW:
  size: 0.1
  health: 1.33
  health per star: 0.33
  tamed:
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
Razorback_TW:
  tamed:
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
BlackBear_TW:
  tamed:
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
GrizzlyBear_TW: 
  damage per star: 0.25
  health: 0.9
  health per star: 0.35
  tamed:
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
GDAncientShaman_TW:
  health: 0.85
  health per star: 0.25
GDAncientShaman_rootspawn_TW:
  health: 1.2
  health per star: 0.2
  infusion:
   Chaos: 25
#Ocean
Shark_TW:
  movement speed: 0.8
  effect:
   splitting: 0
##Adjusted Elite Mobs 
ObsidianGolem_TW:
  effect:
    Splitting: 0
  effect power:
    Regenerating: 0.5
    Splitting: 0
##Prowler Adjustments and Tamed
Prowler_TW:
 effect power:
  Regenerating: 0.5
 tamed:
  infusion:
   Other: 0
  effect:
   Quick: 0
   Curious: 0
   Splitting: 0
#DeepNorth
StormWolf_TW:
  damage per star: 0.2
  health per star: 0.5
JotunnWolf_TW:
  damage per star: 0.2
  health per star: 0.5
ArcticBear_TW:
  damage per star: 0.2
  health per star: 0.5
ArcticWolf_TW:
  damage per star: 0.2
  health per star: 0.5
ArcticMammoth_TW:
  damage per star: 0.2
  health per star: 0.5
ArcticSerpent_TW:
  damage per star: 0.2
  health per star: 0.5
ArcticGolem_TW:
  damage per star: 0.2
  health per star: 0.5
  effect:
    Splitting: 0
  effect power:
    Regenerating: 0.5
    Splitting: 0
StormCultist_TW:
  damage per star: 0.2
  health per star: 0.5
StormFenring_TW:
  damage per star: 0.2
  health per star: 0.5
StormWolf_TW:
  damage per star: 0.2
  health per star: 0.5
  
JotunnWolf_TW:
  damage per star: 0.2
  health per star: 0.5
JotunnBladefist_TW:
  damage per star: 0.2
  health per star: 0.5
JotunnShaman_TW:
  damage per star: 0.2
  health per star: 0.5
JotunnBrute_TW:
  damage per star: 0.2
  health per star: 0.5
JotunnJuggernaut_TW:
  damage per star: 0.2
  health per star: 0.5
  
SurtrImp_TW:
  damage per star: 0.2
  health per star: 0.5
SurtrBrute_TW:
  damage per star: 0.2
  health per star: 0.5
SurtrBones_TW:
  damage per star: 0.2
  health per star: 0.5
SurtrHound_TW:
  damage per star: 0.2
  health per star: 0.5
SurtrDrake_TW:
  damage per star: 0.2
  health per star: 0.5
SurtrLegionnaire_TW:
  damage per star: 0.2
  health per star: 0.5
SurtrSeer_TW:
  damage per star: 0.2
  health per star: 0.5
SurtrWarbringer_TW:
  damage per star: 0.2
  health per star: 0.5
DaggerFang_TW:
  damage per star: 0.2
  health per star: 0.5
groups:
  MeadowsTherzie:
    - Fox_TW
    - Sheep_TW
  BlackForestTherzie:
    - Razorback_TW
    - BlackBear_TW
    - GDAncientShaman_TW
    - GreydwarfMage_TW
  SwampTherzie:
    - RottingElk_TW
    - Crawler_TW
    - HelWraith_TW
    - SkeletonMage_TW
  MountainTherzie:
    - ObsidianGolem_TW
    - GrizzlyBear_TW
    - FenringMage_TW
  PlainsTherzie:
    - Prowler_TW
    - GoblinMage_TW
  MistlandsTherzie:
    - CorruptedDvergerMage_TW
    - SummonedSeeker_TW