GreydwarfMage_TW:
  damage: 1.1
  damage per star: 0.1
  effect:
   Splitting: 0
SkeletonMage_TW:
  damage: 1.1
  damage per star: 0.1
  effect:
   Splitting: 0
FenringMage_TW:
  damage: 1.1
  damage per star: 0.1
  effect:
   Splitting: 0
GoblinMage_TW:
  damage: 1.1
  damage per star: 0.1
  effect:
   Splitting: 0
CorruptedDvergerMage_TW:
  damage: 1.1
  damage per star: 0.1
  effect:
   Splitting: 0
Staff_root_TW:
  health: 1.5
  infusion:
   Other: 0
  effect:
   Quick: 0
   Curious: 0
   Splitting: 0
   Armored: 0
SummonedSurtling_TW:
  infusion:
   Other: 0
  effect:
   Quick: 100
   Other: 0
SummonedGolem_TW:
  infusion:
   Other: 0
  effect:
   Quick: 100
   Other: 0