#Meadows
Greyling:
  health: 1.5
  damage: 2
  damage per star: 0.6
Neck:
  damage: 2
  health: 4
  health per star: 2
Boar:
  health: 3
  health per star: 1
#BlackForest
Greydwarf:
  health: 1.25
  damage: 1.6
Greydwarf_Shaman:
  damage: 1.66
  health: 1.66
Skeleton_Poison:
 BlackForest:
  health: 1.5
  health per star: 0.4
  attack speed: 1.5
 Swamp:
  health: 1.8
  health per star: 0.4
  attack speed: 1.5
Skeleton:
 Swamp:
  health: 2.2
  damage: 2.2
  damage per star: 0.4
  attack speed: 1.1
 Mountain:
  health: 2.5
  damage: 3.2
  damage per star: 0.6
  attack speed: 1.15
 Plains:
  health: 2.7
  damage: 4.2
  damage per star: 0.8
  attack speed: 1.2
Skeleton_NoArcher:
 Swamp:
  health: 2.2
  damage: 2.2
  damage per star: 0.4
  attack speed: 1.1
 Mountain:
  health: 2.5
  damage: 3.2
  damage per star: 0.6
  attack speed: 1.15
 Plains:
  health: 2.7
  damage: 4.2
  damage per star: 0.8
  attack speed: 1.2
TentaRoot:
  health: 2.5
  infusion:
   Chaos: 25
#Swamp
Surtling:
 attack speed: 0.8
 movement speed: 0.6
 Meadows:
  damage: 0.6
  damage per star: 0.2
  health: 4
  health per star: 2
  effect:
   splitting: 0
 BlackForest:
  damage: 0.6
  damage per star: 0.2
  health: 4
  health per star: 2
  effect:
   splitting: 0
 Swamp:
  health: 6
  health per star: 4
 Ashlands:
  health: 15
  health per star: 3
#Mountains
Ulv:
  health: 2.2
  health per star: 2.2
Wolf:
  health per star: 1
  damage per star: 0.2
  tamed:
   damage: 0.01
   damage per star: 0
   health: 0.25
   health per star: 0
  key_defeated_Bonemass:
   tamed:
    damage: 0.6
    damage per star: 0.1
    health: 1.2
    health per star: 0.5
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
#Ocean
Serpent:
  effect:
   splitting: 0
#Plains
Deathsquito:
  movement speed: 0.9
  health: 5.2
  damage taken:
    Bows: 0.75
    Crossbows: 0.75
##Adjusted Elite Mobs 
Troll:
  health per star: 0.5
  damage per star: 0.25
  effect power:
    Regenerating: 0.5
  sector:
    count: 5
# Swamp
Abomination:
  health per star: 0.5
  damage per star: 0.25
  effect power:
    Regenerating: 0.5
  sector:
    count: 5
# Mountain
StoneGolem:
  health per star: 0.5
  damage per star: 0.25
  effect:
    Splitting: 0
  effect power:
    Regenerating: 0.5
    Splitting: 0
  sector:
    count: 5
# Plains
GoblinBrute:
  health per star: 0.5
  damage per star: 0.25
  effect power:
    Regenerating: 0.5
  sector:
    count: 5
# Mistlands
SeekerBrood:
  health: 5.2
  damage: 1.4
  damage taken:
    Fire: 0.25
Seeker:
  damage taken:
    Fire: 0.5
Gjall:
  health per star: 0.5
  damage per star: 0.25
  movement speed: 1.2
  effect:
   Quick: 0
  effect power:
    Regenerating: 0.5
  sector:
    count: 5
    
SeekerBrute:
  health per star: 0.5
  damage per star: 0.25
  damage taken:
    Fire: 0.5
  effect power:
    Regenerating: 0.5
  sector:
    count: 5
# Ashlands
Dverger:
  AshLands:
   health: 0.62
   health per star: 0.32
   damage per star: 0.2
FallenValkyrie:
  health per star: 0.5
  damage per star: 0.2
  effect power:
    Regenerating: 0.5
  sector:
    count: 5
Morgen_NonSleeping:
  health per star: 0.5
  damage per star: 0.2
  effect power:
    Regenerating: 0.5
  sector:
    count: 5
BonemawSerpent:
  health per star: 0.5
  damage per star: 0.2
  effect power:
    Regenerating: 0.5
Asksvin:
  health per star: 0.5
  damage per star: 0.2
  effect power:
    Regenerating: 0.5
Charred_Archer:
  damage per star: 0.2
  effect power:
    Regenerating: 0.5
Charred_Melee:
  damage per star: 0.2
  effect power:
    Regenerating: 0.5
Charred_Mage:
  damage per star: 0.2
  effect power:
    Regenerating: 0.5
Charred_Twitcher:
  damage per star: 0.2
  effect power:
    Regenerating: 0.5
Troll_Summoned:
  infusion:
   Other: 0
  effect:
   Other: 0
##Lox Adjustments and Tamed
Lox:
 health per star: 0.5
 damage per star: 0.25
 sector:
  count: 5
 effect power:
  Regenerating: 0.5
 tamed:
  damage: 0.6
  damage per star: 0.1
  health: 1.2
  health per star: 0.3
  infusion:
   Other: 0
  effect:
   Quick: 0
   Curious: 0
   Splitting: 0
## Tamed
All:
 tamed:
  size: 0
  effect:
    Armored: 0
    Splitting: 0
    Curious: 0
    Aggressive: 0
    Quick: 0
    Other: 10
  infusion:
    Poison: 0
    Chaos: 0
    Fire: 0
    Frost: 0
    Lightning: 0
    Spirit: 0
    Other: 0