Fox_TW:
  health: 0.97
  health per star: 0.4
  damage: 1.2
  damage per star: 0.25
  tamed:
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
Razorback_TW:
  size: 0.02
  tamed:
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
BlackBear_TW:
  size: 0.02
  tamed:
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
GrizzlyBear_TW:
  size: 0
  tamed:
   infusion:
    Other: 0
   effect:
    Quick: 0
    Curious: 0
    Splitting: 0
#Ocean
Shark_TW:
  movement speed: 0.8
  effect:
   splitting: 0
   quick: 0
##Adjusted Elite Mobs 
ObsidianGolem_TW:
  effect power:
    Regenerating: 0.5
##Prowler Adjustments and Tamed
Prowler_TW:
 size: 0.04
 effect power:
  Regenerating: 0.5
 tamed:
  infusion:
   Other: 0
  effect:
   Quick: 0
   Curious: 0
   Splitting: 0
#DeepNorth
ArcticBear_TW:
  damage per star: 0.1
  health per star: 0.6
  size: 0
ArcticWolf_TW:
  damage per star: 0.1
  health per star: 0.6
ArcticMammoth_TW:
  damage per star: 0.1
  health per star: 0.6
  size: 0
ArcticSerpent_TW:
  damage per star: 0.1
  health per star: 0.6
ArcticCultist_TW:
  damage per star: 0.1
  health per star: 0.6
ArcticFenring_TW:
  damage per star: 0.1
  health per star: 0.6
ArcticGolem_TW:
  damage per star: 0.1
  health per star: 0.6