groups:
  MeadBase:
  - BarleyWineBase
  - MeadBaseEitrMinor
  - MeadBaseFrostResist
  - MeadBaseHealthMajor
  - MeadBaseHealthMedium
  - MeadBaseHealthMinor
  - MeadBasePoisonResist
  - MeadBaseStaminaLingering
  - MeadBaseStaminaMedium
  - MeadBaseStaminaMinor
  - MeadBaseTasty
  - MeadBaseEitrLingering
  - MeadBaseHealthLingering
  - MeadBaseLightningResist_TW
  - MeadBaseLingeringStaminaMinor_TW
  - MeadBaseLingeringStaminaMedium_TW
  - MeadBaseEitrBlackForest_TW
  - MeadBaseEitrMountain_TW
  CustomFood:
  - HoneyGlazedDeer
  - HoneyGlazedMeat
  - HoneyGlazedNeck
  - HoneyGlazedLox
  - HoneyGlazedFish
  - HoneyGlazedWolf
  - JellyGlazedHare
  - JellyGlazedSeeker
  - CookedEntrails
  - ElkJerky
  - LoxJerky_JH
  - SeekerJerky_JH
  - FishJerky_JH
  - FishStew_JH
  - NeckJerky_JH
  - SerpentJerky_JH
  - FishNLoxSkewer
  - FishMeatSkewer
  - DandelionTea_JH
  ReduceWeight:
  - Stone
  - BlackMarble
  - Flint
  - Coal
  - Tar
  - Obsidian
  - SulfurStone
  - Grausten
  - Chitin
  - CeramicPlate
  WizardryScrolls:
  - ArcaneScroll_DamageBuff_TW
  - ArcaneScroll_SpeedBuff_TW
  - ArcaneScroll_JumpBuff_TW
  - ArcaneScroll_SlowfallBuff_TW
#
all:
    floating: yes
    pickup: yes
# stuff floats in water; everything is pickable
Stackable:
    stack: 200
WizardryScrolls:
    stack: 100
DragonEgg:
    stack: 3
    weight: 100
CryptKey:
    stack: 200
MeadBase:
    stack: 200
mmo_mead_minor:
    stack: 200
mmo_mead_med:
    stack: 200
mmo_mead_greater:
    stack: 200
Food:
    stack: 200
    loss: no
CustomFood:
    stack: 200
    loss: no
Food Backpack:
    loss: no
# food stacks to 200 and doesn't be removed from inventory on death
metal:
    teleportable: no
    stack: 200
    Weight: 10
ore:
    teleportable: no
    stack: 200
    Weight: 10
# ores and metals are not teleportable, stack to 100 and metals weight only 10
ReduceWeight:
    stack: 200
    Weight: 1
# stones stack to 100 and weight only 1
trophy:
    stack: 200
    Weight: 2
boss trophy:
    stack: 200
    Weight: 2
# trophys stack up to 100 and weight only 2
Coins:
    stack: 10000
    weight: 0.05
valuable:
    stack: 200
    weight: 0.05
# make coins, valuables lighter
Wood:
  stack: 1000
  weight: 1
FineWood:
    stack: 1000
    weight: 1
RoundLog:
    stack: 1000
    weight: 1
ElderBark:
    stack: 1000
    weight: 1
YggdrasilWood:
    stack: 1000
    weight: 1
Blackwood:
    stack: 1000
    weight: 1
BorealWood_TW:
    stack: 1000
    weight: 1
BorealPineWood_TW:
    stack: 1000
    weight: 1
ScorchedWood_TW:
    stack: 1000
    weight: 1
EnchantedWoodBlackForest_TW:
    stack: 1000
    weight: 1
EnchantedWoodSwamp_TW:
    stack: 1000
    weight: 1
EnchantedWoodMountain_TW:
    stack: 1000
    weight: 1
EnchantedWoodPlains_TW:
    stack: 1000
    weight: 1
EnchantedWoodMistlands_TW:
    stack: 1000
    weight: 1
# All Wood types stack to 100 and weight half