name: goblin_totempole
itemPrefab: GoblinTotem
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 0
spawnOffset: 1.7
ifHasHealth: 
hiddenChildWhenPicked: Totem
extraDrops:
  drops:
  - GoblinTotem
  dropMin: 1
  dropMax: 2
  dropChance: 0.5
  dropOneOfEach: false
