name: WindPotion_JH
m_weight: 1
m_name: Tail Wind Potion
m_description: Gives you tail wind
clonePrefabName: MeadFrostResist
mockName: 
customIcon: WindPotion_JH.png
material: 
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
m_maxStackSize: 200
m_canBeReparied: true
m_destroyBroken: true
m_dodgeable: false
Attack_status_effect: 
Attack_status_effect_chance: 1
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 4
m_knockback: 50
m_useDurability: false
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 100
m_durabilityPerLevel: 50
m_equipDuration: 1
Attach_Override: None
m_skillType: Swords
m_animationState: OneHanded
m_itemType: Consumable
m_toolTier: 0
m_maxQuality: 1
m_value: 0
ConsumableStatusEffect: SE_WindPotion_JH
AppendToolTip: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects: []
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect: []
  Trail_Effect: []
